import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import {
  HydrationBoundary,
  QueryClient,
  QueryClientProvider,
} from "@tanstack/react-query";
import Providers from "./Providers";
import { CustomGradientIcon, CustomIcon, MailIcon } from "@/components/Icons";
import { LinkIcon } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const queryClient = new QueryClient();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="relative ">
            <div className="fixed top-1/2 left-5 transform -translate-y-1/2 space-y-4 bg-white p-3 shadow-2xl rounded-full z-10">
              <button className="w-12 h-12 bg-gray-100 rounded-full flex items-center justify-center shadow-md hover:bg-gray-200">
                <LinkIcon />
              </button>
              <button className="w-12 h-12 bg-gray-100 rounded-full flex items-center justify-center shadow-md hover:bg-gray-200">
                <MailIcon />
              </button>
              <button className="w-12 h-12 bg-gray-100 rounded-full flex items-center justify-center shadow-md hover:bg-gray-200">
                <CustomIcon />
              </button>
              <button className="w-12 h-12 bg-gray-100 rounded-full flex items-center justify-center shadow-md hover:bg-gray-200">
                <CustomGradientIcon />
              </button>
            </div>
            <div className="lg:px-10 py-5">
              <Header />
              <div className="px-10 md:px-30">{children}</div>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
